spring:
  application:
    name: Jetbrains-Help
  thymeleaf:
    cache: false
server:
  port: 10768
help:
  default-license-name: cikaros.top
  default-assignee-name: Cikaros
  default-expiry-date: 2099-12-31